INSERT INTO COST (ID, COST_VALUE, ADDITIONAL_COST_VALUE) VALUES (1, 10.10, 5.25);
INSERT INTO COST (ID, COST_VALUE, ADDITIONAL_COST_VALUE) VALUES (2, 300.79, 150.15);
INSERT INTO COST (ID, COST_VALUE, ADDITIONAL_COST_VALUE) VALUES (3, 1059.59, 300.19);
INSERT INTO COST (ID, COST_VALUE, ADDITIONAL_COST_VALUE) VALUES (4, 10000, 5000);

INSERT INTO INCOME (ID, INCOME_VALUE) VALUES (1, 25.89);
INSERT INTO INCOME (ID, INCOME_VALUE) VALUES (2, 409.19);
INSERT INTO INCOME (ID, INCOME_VALUE) VALUES (3, 1530.77);
INSERT INTO INCOME (ID, INCOME_VALUE) VALUES (4, 50000);

INSERT INTO PROFIT_LOSS (ID, CALCULATED_PROFIT_OR_LOSS, INCOME_ID, COST_ID) VALUES (1, 10.54, 1, 1);
INSERT INTO PROFIT_LOSS (ID, CALCULATED_PROFIT_OR_LOSS, INCOME_ID, COST_ID) VALUES (2, -41.75, 2, 2);
INSERT INTO PROFIT_LOSS (ID, CALCULATED_PROFIT_OR_LOSS, INCOME_ID, COST_ID) VALUES (3, 170.99, 3, 3);
INSERT INTO PROFIT_LOSS (ID, CALCULATED_PROFIT_OR_LOSS, INCOME_ID, COST_ID) VALUES (4, 35000, 4, 4);