INSERT INTO COST (COST_VALUE, ADDITIONAL_COST_VALUE) VALUES (10.10, 5.25);
INSERT INTO COST (COST_VALUE, ADDITIONAL_COST_VALUE) VALUES (300.79, 150.15);
INSERT INTO COST (COST_VALUE, ADDITIONAL_COST_VALUE) VALUES (1059.59, 300.19);
INSERT INTO COST (COST_VALUE, ADDITIONAL_COST_VALUE) VALUES (10000, 5000);

INSERT INTO INCOME (INCOME_VALUE) VALUES (25.89);
INSERT INTO INCOME (INCOME_VALUE) VALUES (409.19);
INSERT INTO INCOME (INCOME_VALUE) VALUES (1530.77);
INSERT INTO INCOME (INCOME_VALUE) VALUES (50000);

INSERT INTO PROFIT_LOSS (CALCULATED_PROFIT_OR_LOSS, INCOME_ID, COST_ID) VALUES (10.54, 1, 1);
INSERT INTO PROFIT_LOSS (CALCULATED_PROFIT_OR_LOSS, INCOME_ID, COST_ID) VALUES (-41.75, 2, 2);
INSERT INTO PROFIT_LOSS (CALCULATED_PROFIT_OR_LOSS, INCOME_ID, COST_ID) VALUES (170.99, 3, 3);
INSERT INTO PROFIT_LOSS (CALCULATED_PROFIT_OR_LOSS, INCOME_ID, COST_ID) VALUES (35000, 4, 4);