INSERT INTO COST (ID, COST_VALUE, ADDITIONAL_COST_VALUE) VALUES (1, 10.10, 5.25);

INSERT INTO INCOME (ID, INCOME_VALUE) VALUES (1, 25.89);

INSERT INTO PROFIT_LOSS (ID, CALCULATED_PROFIT_OR_LOSS, INCOME_ID, COST_ID) VALUES (1, 10.54, 1, 1);